services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=reymitech
      - POSTGRES_DB=shop-ecommerce
    ports:
      - 5434:5434
    command: ["postgres", "-c", "port=5434"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5434"]
      interval: 10s
      timeout: 5s
      retries: 5
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=reymitech
      - MONGO_INITDB_DATABASE=shop-ecommerce
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db

volumes:
  mongo-data: